name: Node.js application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Ejecutar pruebas
      run: node app_test.js

    - name: Ejecutar la app
      run: node app.js

    - name: Simular el deploy
      run: echo "Simular que se esta desplegando"

    - name: Construir la imagen de docker
      run: docker build -t ghcr.io/lorecami/hello-camila-node:1.0.0 .

    - name: Login en Github container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Publicar la imagen
      run: docker push ghcr.io/lorecami/hello-camila-node:1.0.0